-- Ship-gym equipment catalog: Smith machine, cable functional trainer, leg extension/curl,
-- dumbbells + adjustable bench, pull-up rig, Bosu ball, decline bench. Sourced from onboard
-- equipment photos so the crew can log every exercise their gym actually supports.

insert into public.skandi_exercises
  (slug, name, english_name, category, equipment, muscles, media_url, media_page_url, instructions, coach_tips)
values
  ('smith-machine-bench-press','Smith Machine Bench Press','Smith Machine Bench Press','Strength','{"Smith Machine","Bench"}','{"Chest": 55, "Triceps": 30, "Shoulders": 15}'::jsonb,'https://gymvisual.com/img/p/1/7/5/5/7/17557.gif','https://gymvisual.com/animated-gifs/2231-smith-bench-press.html',
   '{"Set the bar height so it starts just above your chest.","Lie back and grip slightly wider than shoulder width.","Lower the bar to your chest under control.","Press up along the fixed vertical rail."}',
   '{"The fixed bar path removes stabilizer work, so focus on driving through your chest.","Keep your feet planted and shoulder blades pinned back."}'),
  ('smith-machine-incline-bench-press','Smith Machine Incline Bench Press','Smith Machine Incline Bench Press','Strength','{"Smith Machine","Bench"}','{"Chest": 50, "Shoulders": 30, "Triceps": 20}'::jsonb,'https://gymvisual.com/img/p/1/4/1/6/5/14165.gif','https://gymvisual.com/animated-gifs/2240-smith-incline-bench-press.html',
   '{"Set the bench to a 30-45 degree incline under the bar.","Unrack and lower the bar to your upper chest.","Press straight up along the rail.","Keep your lower back on the pad."}',
   '{"A steeper incline shifts work to the front delts, keep it moderate for chest.","Do not flare your elbows past 75 degrees."}'),
  ('smith-machine-squat','Smith Machine Squat','Smith Machine Squat','Strength','{"Smith Machine"}','{"Quads": 45, "Glutes": 30, "Hamstrings": 15, "Core": 10}'::jsonb,'https://gymvisual.com/img/p/5/4/9/4/5494.gif','https://gymvisual.com/animated-gifs/2253-smith-squat.html',
   '{"Position the bar across your upper back.","Set your feet slightly ahead of the bar path.","Squat down under control, tracking knees over feet.","Drive through your heels to stand."}',
   '{"The fixed rail lets you push hard without a spotter, but do not let your knees cave in.","Step your feet forward slightly since the bar path is vertical, not natural."}'),
  ('smith-machine-shoulder-press','Smith Machine Shoulder Press','Smith Machine Shoulder Press','Strength','{"Smith Machine","Bench"}','{"Shoulders": 55, "Triceps": 25, "Core": 20}'::jsonb,'https://gymvisual.com/img/p/5/4/9/0/5490.gif','https://gymvisual.com/animated-gifs/2249-smith-shoulder-press.html',
   '{"Set a bench upright under the bar at chin height.","Grip just outside shoulder width.","Press the bar overhead until arms lock out.","Lower with control back to the start."}',
   '{"Brace your core before every rep.","Keep your ribs down, do not overarch your lower back."}'),
  ('smith-machine-bulgarian-split-squat','Smith Machine Bulgarian Split Squat','Smith Machine Bulgarian Split Squat','Strength','{"Smith Machine","Bench"}','{"Quads": 45, "Glutes": 35, "Hamstrings": 15, "Core": 5}'::jsonb,'https://gymvisual.com/img/p/5/4/9/2/5492.gif','https://gymvisual.com/animated-gifs/2251-smith-single-leg-split-squat.html',
   '{"Set the bar across your upper back.","Rest your rear foot on a bench behind you.","Lower until your front thigh is close to parallel.","Drive through your front heel to stand."}',
   '{"Keep most of your weight on the front leg.","Go slightly lighter than your regular squat weight."}'),
  ('smith-machine-bent-over-row','Smith Machine Bent-Over Row','Smith Machine Bent-Over Row','Strength','{"Smith Machine"}','{"Back": 55, "Biceps": 20, "Core": 15, "Shoulders": 10}'::jsonb,'https://gymvisual.com/img/p/2/1/1/0/8/21108.gif','https://gymvisual.com/animated-gifs/3129-smith-bent-over-row.html',
   '{"Hinge at the hips with a flat back.","Grip the bar just outside shoulder width.","Pull the bar toward your lower ribs.","Lower with control without rounding your back."}',
   '{"Keep your knees soft and hips still throughout the set.","Squeeze your shoulder blades together at the top."}'),
  ('cable-lat-pulldown','Cable Lat Pulldown','Cable Lat Pulldown','Strength','{"Cable Machine","Straight Bar"}','{"Back": 55, "Biceps": 25, "Core": 10, "Forearms": 10}'::jsonb,'https://gymvisual.com/img/p/5/7/5/7/5757.gif','https://gymvisual.com/animated-gifs/2516-cable-close-grip-front-lat-pulldown.html',
   '{"Set the pulley to the top position and attach a bar.","Kneel or sit facing the tower and grip the bar.","Pull down toward your upper chest, elbows down and back.","Let the bar rise with control back to full stretch."}',
   '{"Lead with your elbows, not your hands.","Do not lean back excessively to move more weight."}'),
  ('cable-seated-row','Cable Seated Row','Cable Seated Row','Strength','{"Cable Machine"}','{"Back": 50, "Biceps": 25, "Core": 15, "Shoulders": 10}'::jsonb,'https://gymvisual.com/img/p/4/9/5/1/4951.gif','https://gymvisual.com/animated-gifs/1711-cable-seated-wide-grip-row.html',
   '{"Set the pulley low and sit with knees slightly bent.","Grip the handle with arms extended.","Pull toward your torso, squeezing your shoulder blades.","Return with control without rounding your back."}',
   '{"Keep your torso still, do not use momentum from your hips.","Pause briefly at full contraction."}'),
  ('cable-standing-chest-press','Standing Cable Chest Press','Standing Cable Chest Press','Strength','{"Cable Machine"}','{"Chest": 55, "Shoulders": 25, "Triceps": 20}'::jsonb,'https://gymvisual.com/img/p/2/0/5/5/9/20559.gif','https://gymvisual.com/animated-gifs/2526-cable-standing-chest-press.html',
   '{"Set both pulleys to chest height and grab a handle in each hand.","Stand in a split stance facing away from the tower.","Press both handles forward until arms extend.","Return with control, keeping tension on the cables."}',
   '{"Keep a slight forward lean and braced core to stay stable.","Do not let the handles snap back between reps."}'),
  ('cable-crossover-fly','Cable Crossover Fly','Cable Crossover Fly','Strength','{"Cable Machine"}','{"Chest": 65, "Shoulders": 25, "Core": 10}'::jsonb,'https://gymvisual.com/img/p/4/8/8/8/4888.gif','https://gymvisual.com/animated-gifs/1648-cable-crossover-variation.html',
   '{"Set both pulleys above shoulder height with handles attached.","Step forward into a split stance between the towers.","Sweep both handles down and together in front of your chest.","Return slowly, keeping a slight bend in your elbows."}',
   '{"Think about squeezing your chest together, not just moving your arms.","Keep your elbows softly bent throughout, do not turn it into a press."}'),
  ('cable-triceps-pushdown','Cable Triceps Pushdown','Cable Triceps Pushdown','Strength','{"Cable Machine","V Bar"}','{"Triceps": 85, "Forearms": 15}'::jsonb,'https://gymvisual.com/img/p/4/9/7/4/4974.gif','https://gymvisual.com/animated-gifs/1734-cable-triceps-pushdown-v-bar-attachment.html',
   '{"Set the pulley high and attach a V-bar.","Keep your elbows pinned to your sides.","Extend down until your arms are straight.","Return with control without letting your elbows drift."}',
   '{"Avoid leaning on the bar with your bodyweight to move more load.","Keep your wrists neutral."}'),
  ('cable-bicep-curl','Cable Bicep Curl','Cable Bicep Curl','Strength','{"Cable Machine","EZ Bar"}','{"Biceps": 80, "Forearms": 20}'::jsonb,'https://gymvisual.com/img/p/7/0/7/4/7074.gif','https://gymvisual.com/animated-gifs/3471-cable-biceps-curl-sz-bar.html',
   '{"Set the pulley low and attach an EZ-bar.","Stand tall with elbows close to your sides.","Curl the bar up without swinging your torso.","Lower slowly to full extension."}',
   '{"The constant cable tension works well for a strict, controlled curl.","Keep your elbows fixed at your sides."}'),
  ('cable-face-pull','Cable Face Pull','Cable Face Pull','Strength','{"Cable Machine","Rope"}','{"Shoulders": 50, "Back": 35, "Forearms": 15}'::jsonb,'https://gymvisual.com/img/p/2/4/9/7/4/24974.gif','https://gymvisual.com/animated-gifs/14130-cable-standing-face-pull-with-rope.html',
   '{"Set the pulley to face height and attach a rope.","Pull the rope toward your face, splitting the ends apart.","Lead with your elbows high and out to the sides.","Return with control to full stretch."}',
   '{"Great for rear-delt and posture work, use lighter weight and strict form.","Squeeze your shoulder blades at the finish."}'),
  ('cable-woodchopper','Cable Woodchopper','Cable Woodchopper','Core','{"Cable Machine"}','{"Core": 70, "Shoulders": 15, "Glutes": 15}'::jsonb,'https://gymvisual.com/img/p/3/4/1/5/6/34156.gif','https://gymvisual.com/animated-gifs/19083-cable-reverse-woodchop-male.html',
   '{"Set the pulley low (or high for the reverse chop) and grip the handle with both hands.","Rotate your torso and hips to pull the handle across your body.","Control the return back to the start position.","Complete all reps on one side before switching."}',
   '{"Rotate from your core, not just your arms.","Keep a slight bend in your knees throughout."}'),
  ('cable-lateral-raise','Cable Lateral Raise','Cable Lateral Raise','Strength','{"Cable Machine"}','{"Shoulders": 85, "Forearms": 15}'::jsonb,'https://gymvisual.com/img/p/4/9/1/1/4911.gif','https://gymvisual.com/animated-gifs/1586-cable-lateral-raise.html',
   '{"Set the pulley to the lowest position and stand beside the tower.","Grip the handle with the arm farthest from the machine.","Raise your arm out to the side to shoulder height.","Lower with control."}',
   '{"The cable keeps tension on your shoulder through the whole range, unlike dumbbells.","Do not shrug your shoulder up as you raise."}'),
  ('cable-pull-through','Cable Pull-Through','Cable Pull-Through','Strength','{"Cable Machine","Rope"}','{"Glutes": 50, "Hamstrings": 35, "Core": 15}'::jsonb,'https://gymvisual.com/img/p/5/8/9/7/5897.gif','https://gymvisual.com/animated-gifs/2656-cable-pull-through.html',
   '{"Set the pulley low behind you and attach a rope between your legs.","Face away from the tower and hinge at your hips.","Drive your hips forward to stand tall, squeezing your glutes.","Return under control, pushing your hips back."}',
   '{"Think hip hinge, not squat.","Keep a soft bend in your knees the whole set."}'),
  ('leg-extension-machine','Leg Extension','Leg Extension','Strength','{"Leg Extension Machine"}','{"Quads": 95, "Core": 5}'::jsonb,'https://gymvisual.com/img/p/5/3/2/2/5322.gif','https://gymvisual.com/animated-gifs/2082-lever-leg-extension.html',
   '{"Sit with the back pad set so your knees line up with the machine pivot.","Hook your ankles under the pad.","Extend your legs until almost straight.","Lower with control back to the start."}',
   '{"Do not slam the weight stack at the bottom.","Pause briefly at the top for a stronger quad squeeze."}'),
  ('seated-leg-curl-machine','Seated Leg Curl','Seated Leg Curl','Strength','{"Leg Curl Machine"}','{"Hamstrings": 90, "Glutes": 10}'::jsonb,'https://gymvisual.com/img/p/1/0/4/8/2/10482.gif','https://gymvisual.com/animated-gifs/2096-lever-seated-leg-curl.html',
   '{"Sit with the pad resting just above your heels.","Grip the side handles and brace your torso.","Curl your heels down and under the seat.","Return with control to full extension."}',
   '{"Avoid lifting your hips off the seat to move more weight.","Keep your toes relaxed, not pointed."}'),
  ('dumbbell-incline-bench-press','Dumbbell Incline Bench Press','Dumbbell Incline Bench Press','Strength','{"Dumbbells","Bench"}','{"Chest": 50, "Shoulders": 30, "Triceps": 20}'::jsonb,'https://gymvisual.com/img/p/2/0/8/2/3/20823.gif','https://gymvisual.com/animated-gifs/1807-dumbbell-incline-bench-press.html',
   '{"Set the bench to a 30-45 degree incline.","Start with the dumbbells over your upper chest.","Lower with elbows around 45 degrees.","Press up without crashing the dumbbells together."}',
   '{"A steep incline turns this into a shoulder press, keep it moderate.","Control the descent, do not bounce off your chest."}'),
  ('dumbbell-shoulder-press','Dumbbell Shoulder Press','Dumbbell Shoulder Press','Strength','{"Dumbbells","Bench"}','{"Shoulders": 55, "Triceps": 25, "Core": 20}'::jsonb,'https://gymvisual.com/img/p/5/1/4/6/5146.gif','https://gymvisual.com/animated-gifs/1906-dumbbell-seated-shoulder-press.html',
   '{"Sit on an upright bench with a dumbbell in each hand at shoulder height.","Brace your core and keep your back against the pad.","Press both dumbbells overhead until arms lock out.","Lower with control back to shoulder height."}',
   '{"Do not let the dumbbells drift forward, keep them stacked over your elbows.","Avoid arching your lower back off the pad."}'),
  ('dumbbell-lateral-raise','Dumbbell Lateral Raise','Dumbbell Lateral Raise','Strength','{"Dumbbells"}','{"Shoulders": 90, "Forearms": 10}'::jsonb,'https://gymvisual.com/img/p/1/9/1/5/1/19151.gif','https://gymvisual.com/animated-gifs/1835-dumbbell-lateral-raise.html',
   '{"Stand tall with a dumbbell in each hand at your sides.","Raise both arms out to the sides to shoulder height.","Keep a slight bend in your elbows.","Lower with control."}',
   '{"Lead with your elbows, not your hands.","Use lighter weight than you think, strict form matters most here."}'),
  ('dumbbell-single-arm-row','Single-Arm Dumbbell Row','Single-Arm Dumbbell Row','Strength','{"Dumbbells","Bench"}','{"Back": 55, "Biceps": 25, "Core": 10, "Shoulders": 10}'::jsonb,'https://gymvisual.com/img/p/2/1/8/3/4/21834.gif','https://gymvisual.com/animated-gifs/12353-dumbbell-single-arm-bent-over-row.html',
   '{"Place one knee and hand on a bench for support.","Hold a dumbbell in the opposite hand, arm extended.","Pull the dumbbell toward your hip, elbow close to your body.","Lower with control to full stretch."}',
   '{"Keep your back flat and avoid twisting your torso to lift the weight.","Squeeze your shoulder blade at the top of each rep."}'),
  ('dumbbell-goblet-squat','Dumbbell Goblet Squat','Dumbbell Goblet Squat','Strength','{"Dumbbells"}','{"Quads": 45, "Glutes": 30, "Core": 15, "Hamstrings": 10}'::jsonb,'https://gymvisual.com/img/p/1/0/2/8/3/10283.gif','https://gymvisual.com/animated-gifs/3795-dumbbell-goblet-squat.html',
   '{"Hold a dumbbell vertically against your chest with both hands.","Set your feet shoulder-width apart.","Squat down between your knees, keeping your chest up.","Drive through your heels to stand."}',
   '{"Great for learning squat depth and bracing before loading a barbell.","Keep your elbows brushing your knees at the bottom."}'),
  ('dumbbell-walking-lunge','Dumbbell Walking Lunge','Dumbbell Walking Lunge','Strength','{"Dumbbells"}','{"Quads": 40, "Glutes": 35, "Hamstrings": 15, "Core": 10}'::jsonb,'https://gymvisual.com/img/p/7/0/2/5/7025.gif','https://gymvisual.com/animated-gifs/3422-dumbbell-walking-lunges.html',
   '{"Hold a dumbbell in each hand at your sides.","Step forward into a lunge, lowering your back knee toward the floor.","Drive through your front heel to stand and step into the next lunge.","Keep your torso upright throughout."}',
   '{"Take a long enough stride that your front knee stays over your ankle.","Control each landing instead of dropping into it."}'),
  ('dumbbell-hammer-curl','Dumbbell Hammer Curl','Dumbbell Hammer Curl','Strength','{"Dumbbells"}','{"Biceps": 55, "Forearms": 45}'::jsonb,'https://gymvisual.com/img/p/5/0/4/6/5046.gif','https://gymvisual.com/animated-gifs/1806-dumbbell-hammer-curl.html',
   '{"Stand tall with a dumbbell in each hand, palms facing your body.","Keep your elbows close to your sides.","Curl both dumbbells up without rotating your wrists.","Lower slowly to full extension."}',
   '{"The neutral grip hits your forearms harder than a regular curl.","Avoid swinging your shoulders to move the weight."}'),
  ('hanging-leg-raise','Hanging Leg Raise','Hanging Leg Raise','Core','{"Pull-up bar","Bodyweight"}','{"Core": 80, "Forearms": 20}'::jsonb,'https://gymvisual.com/img/p/5/2/1/1/5211.gif','https://gymvisual.com/animated-gifs/1971-hanging-leg-raise.html',
   '{"Hang from the pull-up bar with arms fully extended.","Brace your core and avoid swinging.","Raise your legs until close to parallel with the floor.","Lower with control back to a dead hang."}',
   '{"Bend your knees slightly if straight-leg raises are too hard.","Exhale as you lift to keep your ribs down."}'),
  ('bosu-ball-squat','Bosu Ball Squat','Bosu Ball Squat','Core','{"Bosu Ball","Bodyweight"}','{"Quads": 40, "Glutes": 25, "Core": 25, "Hamstrings": 10}'::jsonb,'https://gymvisual.com/img/p/7/4/2/1/7421.gif','https://gymvisual.com/animated-gifs/3674-squat-on-bosu-ball.html',
   '{"Stand on the dome side of the Bosu ball with feet shoulder-width apart.","Brace your core to stay balanced.","Squat down under control, keeping your chest up.","Drive back up to standing without losing balance."}',
   '{"Start bodyweight only, the instability is the challenge here.","Keep your eyes on a fixed point to help balance."}'),
  ('push-up-bosu-ball','Push-Up on Bosu Ball','Push-Up on Bosu Ball','Calisthenics','{"Bosu Ball","Bodyweight"}','{"Chest": 45, "Core": 30, "Triceps": 15, "Shoulders": 10}'::jsonb,'https://gymvisual.com/img/p/6/5/7/4/6574.gif','https://gymvisual.com/animated-gifs/3080-push-up-on-bosu-ball.html',
   '{"Grip the sides of the Bosu ball dome with hands slightly wider than shoulders.","Set your body in a straight line from head to heels.","Lower your chest toward the ball under control.","Press back up without losing balance."}',
   '{"The instability adds extra core and stabilizer work over a regular push-up.","Keep your hips from sagging."}'),
  ('decline-sit-up','Decline Sit-Up','Decline Sit-Up','Core','{"Decline Bench"}','{"Core": 90, "Hip Flexors": 10}'::jsonb,'https://gymvisual.com/img/p/2/0/2/5/8/20258.gif','https://gymvisual.com/animated-gifs/1775-decline-sit-up.html',
   '{"Hook your feet under the pads on the decline bench.","Cross your arms over your chest or hold behind your head.","Curl your torso up until your torso is upright.","Lower with control back to the bench."}',
   '{"Move slower on the way down, that is where most of the work happens.","Stop lowering just before your back is flat to keep tension on your abs."}')
on conflict (slug) do update set
  name = excluded.name,
  english_name = excluded.english_name,
  category = excluded.category,
  equipment = excluded.equipment,
  muscles = excluded.muscles,
  media_url = excluded.media_url,
  media_page_url = excluded.media_page_url,
  instructions = excluded.instructions,
  coach_tips = excluded.coach_tips,
  updated_at = now();
