-- Personal calisthenics catalog: handstand, front lever, back lever, and planche
-- progression lines, plus supporting push/pull/legs/core skill work. Muscle keys
-- are restricted to the taxonomy skandi-recovery.js recognizes (Chest, Back, Quads,
-- Hamstrings, Glutes, Shoulders, Core, Biceps, Triceps, Forearms, Calves) so every
-- entry here counts toward the Body tab's fatigue tracking.

insert into public.skandi_exercises
  (slug, name, english_name, category, equipment, muscles, media_page_url, instructions, coach_tips)
values
  ('wall-handstand','Wall Handstand','Wall Handstand','Calisthenics','{"Wall","Bodyweight"}','{"Shoulders":50,"Core":30,"Triceps":15,"Forearms":5}'::jsonb,null,
   '{"Kick up to a handstand facing the wall, chest close to it.","Stack shoulders over wrists and squeeze your glutes and ribs down.","Press the floor away and hold a hollow body line.","Come down with control, one foot at a time."}',
   '{"Practice wrist prep before every session.","Breathe steadily instead of holding your breath."}'),
  ('freestanding-handstand','Freestanding Handstand','Freestanding Handstand','Calisthenics','{"Bodyweight"}','{"Shoulders":45,"Core":35,"Forearms":10,"Triceps":10}'::jsonb,null,
   '{"Kick up away from any wall, spotting a point on the floor.","Balance by micro-adjusting finger pressure, not by bending at the hips.","Keep a hollow, slightly banana-shaped line.","Step out of the handstand under control when balance breaks."}',
   '{"Fall out safely by cartwheeling or stepping down early.","Log hold time, not reps, to track balance progress."}'),
  ('frog-stand','Frog Stand','Frog Stand','Calisthenics','{"Bodyweight"}','{"Shoulders":35,"Core":40,"Forearms":15,"Biceps":10}'::jsonb,null,
   '{"Squat down and place both hands flat on the floor shoulder-width apart.","Rest your knees on the backs of your upper arms, near the elbows.","Lean your weight forward onto your hands until your feet lift off.","Hold the balance, looking slightly forward, not straight down."}',
   '{"This is the gateway skill to crow pose and later handstand balance.","Keep elbows bent at roughly 90 degrees as the shelf for your knees."}'),
  ('front-lever-tuck','Front Lever Tuck','Front Lever Tuck','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":45,"Core":30,"Biceps":15,"Shoulders":10}'::jsonb,null,
   '{"Hang from the bar with a shoulder-width overhand grip.","Pull your shoulder blades down and pull your knees to your chest.","Lean your torso back until it is roughly horizontal.","Hold, keeping your back flat and arms straight."}',
   '{"Keep arms locked straight, all the lean comes from the shoulders and lats.","Start with shorter holds and add time before progressing the tuck."}'),
  ('front-lever-advanced-tuck','Front Lever Advanced Tuck','Front Lever Advanced Tuck','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":48,"Core":32,"Biceps":12,"Shoulders":8}'::jsonb,null,
   '{"Set up as in the tuck front lever, hanging with straight arms.","Extend your hips so your thighs come away from your chest, knees still bent.","Keep your torso horizontal and shoulder blades depressed.","Hold, keeping the extended tuck compact and controlled."}',
   '{"Only extend the hips as far as you can keep your back flat.","This is the biggest jump in difficulty in the front lever line, be patient here."}'),
  ('front-lever-straddle','Front Lever Straddle','Front Lever Straddle','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":50,"Core":30,"Biceps":12,"Shoulders":8}'::jsonb,null,
   '{"From a horizontal hang, extend both legs straight and wide into a straddle.","Keep arms locked and shoulder blades pulled down.","Hold your torso and legs in one horizontal line.","Squeeze your legs back in to release the hold with control."}',
   '{"Widening the straddle makes it easier, narrow it as you get stronger.","Point your toes to keep the whole line tight."}'),
  ('front-lever-full','Front Lever Full','Front Lever Full','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":52,"Core":30,"Biceps":10,"Shoulders":8}'::jsonb,null,
   '{"Hang with straight arms and pull into a horizontal body line, legs together and straight.","Keep your entire body rigid from shoulders to toes.","Hold the position, breathing steadily.","Lower under control back to a dead hang."}',
   '{"If your hips sag, you are not ready for full extension yet, regress to straddle.","Film yourself from the side to check you are truly horizontal."}'),
  ('one-leg-front-lever','One-Leg Front Lever','One-Leg Front Lever','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":52,"Core":30,"Biceps":10,"Shoulders":8}'::jsonb,null,
   '{"From the full front lever, extend one leg straight while the other drops toward a bent tuck.","Keep your straight leg in line with your torso, hips level.","Hold the asymmetric line, keeping shoulders and lats braced.","Switch legs between sets to train both sides."}',
   '{"This regresses the full lever slightly on the bent-leg side, use it to build toward one-arm work.","Keep your hips square, do not let them twist toward the bent leg."}'),
  ('one-arm-front-lever','One-Arm Front Lever','One-Arm Front Lever','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":55,"Core":28,"Biceps":12,"Forearms":5}'::jsonb,null,
   '{"Master the two-arm full front lever with long holds before attempting this.","Hang from one arm, using the free arm out to the side for balance only.","Pull your working-side shoulder blade down and back to lift into the horizontal line.","Hold briefly, then release by lowering under control."}',
   '{"Expect this to take much longer on your working side, train both arms evenly over time.","A slight body rotation toward the working arm is normal, do not fight it too hard early on."}'),
  ('back-lever-tuck','Back Lever Tuck','Back Lever Tuck','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":45,"Shoulders":25,"Core":20,"Forearms":10}'::jsonb,null,
   '{"Start in a support hold or skin-the-cat rotation above the bar.","Rotate through until your body hangs below the bar, arms straight behind you.","Tuck your knees to your chest and keep your back rounded slightly.","Hold, then rotate back up or lower out with control."}',
   '{"Use a false grip or straight wrists, whichever feels safer on your shoulders.","Exit slowly, this position can strain the shoulders if you drop out fast."}'),
  ('back-lever-straddle','Back Lever Straddle','Back Lever Straddle','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":48,"Shoulders":24,"Core":20,"Forearms":8}'::jsonb,null,
   '{"From the tuck back lever, extend your legs into a wide straddle.","Keep your arms straight and shoulders pulled into extension.","Hold your torso and legs in one line below the bar.","Bend your knees back in to exit the hold safely."}',
   '{"Keep your head neutral, do not crane your neck to see the floor.","A wider straddle reduces the lever arm, narrow it as you progress."}'),
  ('back-lever-full','Back Lever Full','Back Lever Full','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":50,"Shoulders":24,"Core":18,"Forearms":8}'::jsonb,null,
   '{"Rotate into the back lever with legs together and fully extended.","Keep your whole body in one straight line below the bar.","Hold, keeping your shoulders actively pulled into extension, not just hanging passively.","Rotate back up to support or tuck the knees to exit."}',
   '{"This loads the shoulders in a vulnerable position, warm up thoroughly first.","Keep holds short at first and build duration gradually."}'),
  ('planche-lean','Planche Lean','Planche Lean','Calisthenics','{"Bodyweight"}','{"Shoulders":45,"Chest":25,"Core":20,"Triceps":10}'::jsonb,null,
   '{"Set your hands on the floor, fingers spread, slightly turned out.","Lean your shoulders forward past your hands, keeping arms straight.","Protract your shoulder blades and squeeze your whole body tight.","Hold the lean, then rock back to release."}',
   '{"This is the foundation drill for every planche progression, do it often.","Keep pushing the floor away to protect your shoulders."}'),
  ('tuck-planche','Tuck Planche','Tuck Planche','Calisthenics','{"Bodyweight","Parallettes"}','{"Shoulders":45,"Chest":20,"Core":25,"Triceps":10}'::jsonb,null,
   '{"From a planche lean or support hold, tuck your knees to your chest.","Shift your weight forward until your feet lift off the ground.","Keep arms straight and shoulder blades protracted.","Hold, then set your feet back down with control."}',
   '{"Keep the tuck tight and compact, a loose tuck makes balance much harder.","Round your upper back slightly to keep the center of mass over your hands."}'),
  ('advanced-tuck-planche','Advanced Tuck Planche','Advanced Tuck Planche','Calisthenics','{"Bodyweight","Parallettes"}','{"Shoulders":45,"Chest":20,"Core":27,"Triceps":8}'::jsonb,null,
   '{"From tuck planche, extend your hips so your thighs move away from your torso.","Keep your knees bent and shins roughly parallel to the floor.","Maintain full shoulder protraction and straight arms.","Hold, then bring your knees back in to release."}',
   '{"This is a big jump from the basic tuck, expect it to take real time.","Keep your head in a neutral position, do not look up."}'),
  ('straddle-planche','Straddle Planche','Straddle Planche','Calisthenics','{"Bodyweight","Parallettes"}','{"Shoulders":48,"Core":27,"Chest":17,"Triceps":8}'::jsonb,null,
   '{"From advanced tuck, extend both legs out into a wide straddle.","Keep your body as horizontal as you can manage.","Keep arms locked and shoulders protracted hard.","Bring your legs back together and down to exit."}',
   '{"A wider straddle is easier, gradually narrow it over time.","Point your toes and keep your legs active, not limp."}'),
  ('full-planche','Full Planche','Full Planche','Calisthenics','{"Bodyweight","Parallettes"}','{"Shoulders":50,"Core":28,"Chest":14,"Triceps":8}'::jsonb,null,
   '{"Extend into a horizontal hold with legs together and fully straight.","Keep your whole body rigid and parallel to the floor.","Hold, breathing steadily instead of bracing your breath.","Lower your feet back down under control to finish."}',
   '{"Most people never need more than short, clean holds here, quality over duration.","If your hips sag, that is a sign to regress back to straddle for more volume."}'),
  ('l-sit','L-Sit','L-Sit','Calisthenics','{"Parallettes","Bodyweight"}','{"Core":55,"Shoulders":20,"Triceps":15,"Forearms":10}'::jsonb,null,
   '{"Support yourself on parallettes or the floor with arms straight.","Lift both legs out in front of you, parallel to the floor.","Keep your shoulders down and away from your ears.","Hold the position, then lower your legs with control."}',
   '{"Point your toes and keep your legs straight to keep tension high.","If it is too hard, bend one or both knees and build up from there."}'),
  ('human-flag','Human Flag','Human Flag','Calisthenics','{"Pole","Bodyweight"}','{"Core":30,"Shoulders":25,"Back":20,"Chest":15,"Forearms":10}'::jsonb,null,
   '{"Grip a vertical pole with one hand high, pulling, and one hand low, pressing.","Brace your whole body and lift your hips and legs to horizontal.","Keep your entire body in one straight line out from the pole.","Lower down with control to release the hold."}',
   '{"Practice the tucked or one-leg version first to build the grip and shoulder strength safely.","Alternate which hand is on top to train both sides evenly."}'),
  ('pike-push-up','Pike Push-Up','Pike Push-Up','Calisthenics','{"Bodyweight"}','{"Shoulders":55,"Triceps":25,"Core":20}'::jsonb,null,
   '{"Set up in a downward-dog position, hips high and hands under your shoulders.","Bend your elbows to lower the crown of your head toward the floor.","Keep your hips high throughout the movement.","Press back up until your arms are straight."}',
   '{"Walk your feet closer to your hands to increase the difficulty.","Keep your neck neutral, do not tuck your chin to your chest."}'),
  ('handstand-push-up-wall','Handstand Push-Up (Wall)','Handstand Push-Up (Wall)','Calisthenics','{"Wall","Bodyweight"}','{"Shoulders":55,"Triceps":30,"Core":15}'::jsonb,null,
   '{"Kick up into a wall handstand, chest facing the wall.","Lower yourself by bending your elbows until your head lightly taps the floor.","Keep your body tight and hollow throughout the descent.","Press back up to full lockout."}',
   '{"Use a folded mat or pillow under your head until your range of motion is reliable.","Only add range as your shoulders can control it, do not rush depth."}'),
  ('pseudo-planche-push-up','Pseudo Planche Push-Up','Pseudo Planche Push-Up','Calisthenics','{"Bodyweight"}','{"Shoulders":40,"Chest":30,"Triceps":20,"Core":10}'::jsonb,null,
   '{"Set your hands lower than usual, near your hips, fingers pointing toward your feet.","Lean your shoulders forward past your hands before you start the rep.","Lower your chest close to the floor while holding the forward lean.","Press back up without losing the lean."}',
   '{"Keep your elbows close to your body, do not flare them out.","This builds the exact lean and pressing strength the planche needs."}'),
  ('archer-push-up','Archer Push-Up','Archer Push-Up','Calisthenics','{"Bodyweight"}','{"Chest":45,"Triceps":25,"Shoulders":20,"Core":10}'::jsonb,null,
   '{"Set your hands wide, well outside shoulder width.","Shift your weight to one side, bending that elbow while the other arm stays straight.","Lower until your bent-arm shoulder is near the floor.","Push back to center and repeat on the other side."}',
   '{"Keep the straight arm active, not just along for the ride.","This is a direct stepping stone toward a one-arm push-up."}'),
  ('muscle-up-bar','Muscle-Up (Bar)','Muscle-Up (Bar)','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":40,"Chest":20,"Triceps":20,"Biceps":10,"Core":10}'::jsonb,null,
   '{"Start from a dead hang with a false grip if you use one.","Pull explosively, driving your chest toward the bar.","Transition by rolling over the bar as your pull finishes.","Press out to full lockout above the bar."}',
   '{"The transition is timing, not just strength, drill it separately with a lower bar if needed.","Keep the pull close to the bar the whole way up."}'),
  ('archer-pull-up','Archer Pull-Up','Archer Pull-Up','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":50,"Biceps":30,"Forearms":10,"Core":10}'::jsonb,null,
   '{"Grip the bar wide, wider than a normal pull-up.","Pull your body toward one hand, keeping the other arm mostly straight.","Touch that shoulder near the bar at the top.","Lower with control and repeat, alternating sides."}',
   '{"Keep the straight arm engaged and pulling slightly, not just hanging.","This builds directly toward a one-arm pull-up."}'),
  ('typewriter-pull-up','Typewriter Pull-Up','Typewriter Pull-Up','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Back":50,"Biceps":25,"Forearms":15,"Core":10}'::jsonb,null,
   '{"Pull up to the top of a wide-grip pull-up, chin over the bar.","Shift your body sideways toward one hand while staying at the top.","Shift back across to the other hand without dropping height.","Lower down with control after both sides."}',
   '{"Keep your chin at bar height the whole time you shift side to side.","Move slowly, speed just skips the hard part."}'),
  ('skin-the-cat','Skin the Cat','Skin the Cat','Calisthenics','{"Pull-up bar","Bodyweight"}','{"Shoulders":35,"Back":25,"Core":30,"Forearms":10}'::jsonb,null,
   '{"Hang from the bar with an overhand grip.","Tuck your knees and roll your hips up and over, through your arms.","Continue rotating until your body hangs below the bar, inverted.","Reverse the motion with control back to a normal hang."}',
   '{"Go slowly on your first sessions, this is a big shoulder stretch.","Stop the descent early if you feel any shoulder pinching."}'),
  ('pistol-squat','Pistol Squat','Pistol Squat','Calisthenics','{"Bodyweight"}','{"Quads":45,"Glutes":30,"Hamstrings":15,"Core":10}'::jsonb,null,
   '{"Stand on one leg, extending the other leg straight out in front.","Sit back and down, keeping your extended leg off the floor.","Lower until your hip is below your knee, keeping your heel planted.","Drive through your standing heel to return to standing."}',
   '{"Hold your arms out in front for counterbalance if needed.","Use a box or bench under you until you own the full range."}'),
  ('shrimp-squat','Shrimp Squat','Shrimp Squat','Calisthenics','{"Bodyweight"}','{"Quads":45,"Glutes":30,"Hamstrings":15,"Core":10}'::jsonb,null,
   '{"Stand on one leg and grab the ankle of your other leg behind you.","Bend your standing knee, lowering that back knee toward the floor.","Keep your torso upright and core braced throughout.","Push through your standing leg to return to standing."}',
   '{"Let your back knee lightly kiss the floor as a depth marker.","This trains single-leg strength without needing much balance skill."}'),
  ('nordic-curl','Nordic Curl','Nordic Curl','Calisthenics','{"Bodyweight"}','{"Hamstrings":75,"Glutes":15,"Core":10}'::jsonb,null,
   '{"Kneel with your ankles anchored or held down by a partner.","Keeping your hips extended, lower your torso forward as slowly as you can.","Use your hamstrings to control the descent for as long as possible.","Catch yourself with your hands and push back up, or use your hamstrings to pull back if strong enough."}',
   '{"Start with a small range you can control, extend it as you get stronger.","This is one of the best injury-prevention exercises for sprinting and jumping."}'),
  ('jump-squat','Jump Squat','Jump Squat','Calisthenics','{"Bodyweight"}','{"Quads":40,"Glutes":30,"Calves":20,"Hamstrings":10}'::jsonb,null,
   '{"Stand with feet shoulder-width apart.","Squat down to about half depth.","Explode upward, driving through your whole foot into a jump.","Land softly, absorbing through your ankles, knees, and hips."}',
   '{"Land quietly, that is a sign of good force absorption.","Rest fully between sets, this is a power exercise, not a conditioning one."}'),
  ('dragon-flag','Dragon Flag','Dragon Flag','Calisthenics','{"Bench","Bodyweight"}','{"Core":70,"Back":15,"Shoulders":15}'::jsonb,null,
   '{"Lie on a bench and grip behind your head for anchoring.","Lift your legs and hips off the bench, supporting on your upper back and shoulders.","Lower your body as one straight rigid line, hips leading.","Stop before your lower back arches, then lift back up."}',
   '{"Only lower as far as you can keep your body perfectly straight.","Regress to bent knees or a smaller range before chasing a full straight-body flag."}'),
  ('hollow-body-hold','Hollow Body Hold','Hollow Body Hold','Calisthenics','{"Bodyweight"}','{"Core":85,"Shoulders":15}'::jsonb,null,
   '{"Lie on your back and press your lower back flat into the floor.","Lift your shoulders and legs slightly off the ground.","Reach your arms overhead or keep them at your sides for an easier version.","Hold the position without letting your lower back arch off the floor."}',
   '{"This shape is the foundation for handstands, levers, and the planche, drill it often.","Bend your knees if you cannot keep your lower back flat with legs straight."}'),
  ('v-up','V-Up','V-Up','Calisthenics','{"Bodyweight"}','{"Core":85,"Quads":15}'::jsonb,null,
   '{"Lie flat on your back with arms extended overhead.","Simultaneously lift your legs and torso, reaching your hands toward your feet.","Balance briefly at the top in a V shape.","Lower back down with control, keeping tension in your abs."}',
   '{"Keep your legs as straight as you can manage.","Exhale on the way up to help engage your deep core."}')
on conflict (slug) do update set
  name = excluded.name,
  english_name = excluded.english_name,
  category = excluded.category,
  equipment = excluded.equipment,
  muscles = excluded.muscles,
  media_page_url = excluded.media_page_url,
  instructions = excluded.instructions,
  coach_tips = excluded.coach_tips,
  updated_at = now();
